services:
  mongodb:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_CLUSTER: ${MONGODB_CLUSTER}
      MONGODB_DB_NAME: ${MONGODB_DB_NAME}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:


